// Andy Miller 2015

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.*/
 
var maxN = 4000000;

function fibonacci(secondToLast, last, sequence, maxN ) {
    //return fibonacci sequence as array given input bounds
    if ((last + secondToLast) < maxN){
        sequence.push(last+secondToLast); 
        sequence = fibonacci(sequence[sequence.length - 2],sequence[sequence.length - 1],sequence,maxN);
    } 
  return sequence;
}

fibSequence = fibonacci(1,2,[1,2],maxN);
console.log(fibSequence);

var evenTerms = fibSequence.filter(function(dummy){return dummy%2 == 0});
console.log(evenTerms); 
console.log(evenTerms.reduce(function(total,num){return total + num }, 0));
//4613732 